changelog:

  exclude:
    labels:
      - "no changelog"

  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"

    - title: Features
      labels:
        - "feature"

    - title: Bug Fixes
      labels:
        - "bug: crash"
        - "bug: gameplay"

    - title: Other Changes
      labels:
        - "*"
